export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const POST_MARKER = "POST_MARKER";
export const DELETE_MARKER = "DELETE_MARKER";
export const MARKERS_LOADING = "MARKERS_LOADING";
export const GET_MARKERS = "GET_MARKERS";
export const UPDATE_MARKER = "UPDATE_MARKER";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_USER_MARKERS = "GET_USER_MARKERS";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
