export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_NAME = "SET_USER_NAME";

export const MARKERS_LOADING = "MARKERS_LOADING";
export const POST_MARKER = "POST_MARKER";
export const DELETE_MARKER = "DELETE_MARKER";
export const GET_MARKERS = "GET_MARKERS";
export const UPDATE_MARKER = "UPDATE_MARKER";
export const UPDATE_USER_IN_MARKERS = "UPDATE_USER_IN_MARKERS";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_LOADING_STOP = "PROFILE_LOADING_STOP";
export const GET_PROFILE = "GET_PROFILE";
export const SET_PROFILE_PHOTO = "SET_PROFILE_PHOTO";
export const GET_USER_MARKERS = "GET_USER_MARKERS";
export const UPDATE_USER_MARKER = "UPDATE_USER_MARKER";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const ADMIN_LOADING = "ADMIN_LOADING";
export const GET_ADMIN_MARKERS = "GET_ADMIN_MARKERS";
